- name: Check if swap file exists
  stat:
    path: "{{ swap_file }}"
  register: swap_file_check

- name: Create swap file
  command: fallocate -l {{ swap_size_mb }}M {{ swap_file }}
  become: yes
  when: not swap_file_check.stat.exists

- name: Create swap space
  command: dd if=/dev/zero of={{ swap_file }} bs=1M count={{ swap_size_mb }}
  become: yes
  when: not swap_file_check.stat.exists

- name: Set permissions on swap file
  file:
    path: "{{ swap_file }}"
    mode: 0600
  become: yes

- name: Format swap file
  command: mkswap {{ swap_file }}
  become: yes
  when: not swap_file_check.stat.exists

- name: Add to fstab
  lineinfile:
    dest: /etc/fstab
    regexp: "{{ swap_file }}"
    line: "{{ swap_file }} none swap sw 0 0"
  become: yes

- name: Turn on swap
  command: swapon -a
  become: yes

- name: Set swapiness
  sysctl:
    name: vm.swappiness
    value: "{{ swap_vm_swappiness }}"
  become: yes
